spring:
    jackson:
        time-zone: UTC
    application:
        name: admin-service
    datasource:
        url: jdbc:postgresql://localhost:15432/saas_gateway?options=-c%20TimeZone=UTC
        username: postgres
        password: postgres

    jpa:
        open-in-view: false

        hibernate:
            ddl-auto: none

        properties:
            hibernate:
                jdbc:
                    time_zone: UTC
                format_sql: true

    flyway:
        enabled: true

server:
  port: 8081