spring:
    datasource:
        url: jdbc:postgresql://localhost:5433/saas_gateway
        username: postgres
        password: postgres

    jpa:
        open-in-view: false

        hibernate:
            ddl-auto: validate

        properties:
            hibernate:
                format_sql: true


    application:
        name: gateway-service



server:
    port: 8082